// Copyright (C) Ronaldo Veloso. All Rights Reserved.

#pragma once

#include "/Engine/Public/Platform.ush"

RWTexture2D<float4> OutTexture;
RWBuffer<float> FluidData;

[numthreads(1, 1, 1)]
void MainCS(uint3 DTid : SV_DispatchThreadID)
{
    // SV_DispatchThreadID.x * sizeof(FFluidSimulationVertex)
    const uint Current = DTid.x * 3;

    OutTexture[DTid.xy] = float4(FluidData[Current + 0], FluidData[Current + 1], FluidData[Current + 2], 1.0f);
}